-- Seed default exercises (available to all users)
INSERT INTO public.exercises (name, muscle_group, is_default, user_id) VALUES
  ('Barbell Bench Press', 'Chest', true, NULL),
  ('Incline Dumbbell Press', 'Chest', true, NULL),
  ('Cable Flyes', 'Chest', true, NULL),
  ('Push-ups', 'Chest', true, NULL),
  ('Barbell Back Squat', 'Legs', true, NULL),
  ('Romanian Deadlift', 'Legs', true, NULL),
  ('Leg Press', 'Legs', true, NULL),
  ('Leg Curl', 'Legs', true, NULL),
  ('Calf Raises', 'Legs', true, NULL),
  ('Lunges', 'Legs', true, NULL),
  ('Pull-ups', 'Back', true, NULL),
  ('Barbell Row', 'Back', true, NULL),
  ('Lat Pulldown', 'Back', true, NULL),
  ('Seated Cable Row', 'Back', true, NULL),
  ('Overhead Press', 'Shoulders', true, NULL),
  ('Lateral Raises', 'Shoulders', true, NULL),
  ('Face Pulls', 'Shoulders', true, NULL),
  ('Front Raises', 'Shoulders', true, NULL),
  ('Barbell Curl', 'Arms', true, NULL),
  ('Tricep Pushdown', 'Arms', true, NULL),
  ('Hammer Curl', 'Arms', true, NULL),
  ('Skull Crushers', 'Arms', true, NULL),
  ('Dumbbell Curl', 'Arms', true, NULL),
  ('Conventional Deadlift', 'Back', true, NULL),
  ('Plank', 'Core', true, NULL),
  ('Hanging Leg Raise', 'Core', true, NULL),
  ('Cable Crunch', 'Core', true, NULL),
  ('Russian Twist', 'Core', true, NULL)
ON CONFLICT DO NOTHING;
